"""FHIR R4 client operations: Patient/Encounter reads (guide §4) and the
DocumentReference/Condition write-back (guide §5), all conformance-checked."""

import base64
from datetime import UTC, datetime

from smart_sandbox.checks import Checker
from smart_sandbox.http import SafeResponse, safe_request
from smart_sandbox.jsonval import as_list, as_object, as_str
from smart_sandbox.models import CheckSeverity, Step, new_step

SAMPLE_NOTE_TITLE = "Consultation - Sandbox test note"
SAMPLE_NOTE_TEXT = """SYNTHETIC TEST NOTE - GENERATED BY THE TANDEM SMART ON FHIR SANDBOX

Subjective:
The patient presents for evaluation of right ankle pain after twisting the
ankle while running yesterday. No previous ankle injuries. Pain is worst on
weight bearing.

Objective:
Moderate swelling over the lateral malleolus. No bony tenderness. Full range
of motion limited by pain. Neurovascularly intact.

Assessment:
Right ankle sprain, lateral ligament complex.

Plan:
Rest, ice, compression, elevation. Follow up in two weeks if not improving.
"""

SAMPLE_CONDITIONS: list[tuple[str, str, str]] = [
    (
        "S93.401A",
        "Sprain of unspecified ligament of right ankle, initial encounter",
        "Right ankle sprain",
    ),
    (
        "M79.671",
        "Pain in right foot",
        "Right foot pain",
    ),
]


def _fhir_headers(access_token: str) -> dict[str, str]:
    return {
        "Authorization": f"Bearer {access_token}",
        "Accept": "application/fhir+json",
    }


async def read_patient(
    *,
    iss: str,
    access_token: str,
    patient_id: str,
    allow_private: bool,
) -> tuple[dict[str, object] | None, Step]:
    """GET Patient/{id} and validate the fields Tandem displays (guide §4.1)."""
    step = new_step("patient", "Read Patient", "§4.1")
    checker = Checker(step)

    response, transcripts = await safe_request(
        "GET",
        f"{iss.rstrip('/')}/Patient/{patient_id}",
        headers=_fhir_headers(access_token),
        allow_private=allow_private,
    )
    step.http.extend(transcripts)

    if not checker.check(
        "patient.reachable",
        "The FHIR server responded",
        "§4",
        response is not None,
        detail=transcripts[-1].error or "",
    ):
        return None, step
    assert response is not None

    if not checker.check(
        "patient.status",
        "GET Patient/{id} returns 200",
        "§4.1",
        response.status_code == 200,
        detail=f"Got HTTP {response.status_code}.",
    ):
        return None, step

    patient = response.json()
    if not checker.check(
        "patient.resource",
        "The response is a Patient resource",
        "§4.1",
        patient is not None and patient.get("resourceType") == "Patient",
    ):
        return None, step
    assert patient is not None

    checker.check(
        "patient.id",
        "Patient.id matches the launch context patient",
        "§4.1",
        patient.get("id") == patient_id,
        detail=f"Expected {patient_id!r}, got {patient.get('id')!r}.",
    )

    names = as_list(patient.get("name"))
    name = as_object(names[0]) if names else None
    has_name = name is not None and bool(
        name.get("text") or (name.get("family") and name.get("given"))
    )
    checker.check(
        "patient.name",
        "Patient.name has text, or family + given",
        "§4.1",
        has_name,
        detail="Tandem displays the name to the clinician for confirmation.",
    )
    checker.check(
        "patient.demographics",
        "birthDate and gender are populated",
        "§4.1",
        bool(patient.get("birthDate")) and bool(patient.get("gender")),
        severity=CheckSeverity.WARN,
        detail="Optional but recommended for disambiguation and note seeding.",
    )
    return patient, step


async def read_encounter(
    *,
    iss: str,
    access_token: str,
    encounter_id: str,
    patient_id: str,
    fhir_user: str | None,
    allow_private: bool,
) -> tuple[dict[str, object] | None, Step]:
    """GET Encounter/{id} and validate the launch context linkage (guide §4.2)."""
    step = new_step("encounter", "Read Encounter", "§4.2")
    checker = Checker(step)

    response, transcripts = await safe_request(
        "GET",
        f"{iss.rstrip('/')}/Encounter/{encounter_id}",
        headers=_fhir_headers(access_token),
        allow_private=allow_private,
    )
    step.http.extend(transcripts)

    if not checker.check(
        "encounter.reachable",
        "The FHIR server responded",
        "§4",
        response is not None,
        detail=transcripts[-1].error or "",
    ):
        return None, step
    assert response is not None

    if not checker.check(
        "encounter.status_code",
        "GET Encounter/{id} returns 200",
        "§4.2",
        response.status_code == 200,
        detail=f"Got HTTP {response.status_code}.",
    ):
        return None, step

    encounter = response.json()
    if not checker.check(
        "encounter.resource",
        "The response is an Encounter resource",
        "§4.2",
        encounter is not None and encounter.get("resourceType") == "Encounter",
    ):
        return None, step
    assert encounter is not None

    subject = as_object(encounter.get("subject"))
    subject_ref = as_str(subject.get("reference")) if subject else None
    checker.check(
        "encounter.subject",
        "Encounter.subject references the launch context patient",
        "§4.2",
        subject_ref is not None and subject_ref.split("/")[-1] == patient_id,
        detail=f"subject.reference: {subject_ref!r}, expected Patient/{patient_id}.",
    )

    participant_refs: list[str] = []
    for item in as_list(encounter.get("participant")) or []:
        participant = as_object(item)
        individual = as_object(participant.get("individual")) if participant else None
        reference = as_str(individual.get("reference")) if individual else None
        if reference is not None:
            participant_refs.append(reference)
    checker.check(
        "encounter.participant",
        "Encounter.participant identifies the responsible practitioner",
        "§4.2",
        bool(participant_refs),
        severity=CheckSeverity.WARN,
    )
    if fhir_user and participant_refs:
        fhir_user_tail = "/".join(fhir_user.split("/")[-2:])
        checker.check(
            "encounter.fhir_user_match",
            "A participant matches the launching user (fhirUser)",
            "§4.2",
            any(ref.endswith(fhir_user_tail) for ref in participant_refs),
            severity=CheckSeverity.WARN,
            detail=(
                f"participants: {participant_refs}, fhirUser: {fhir_user}. "
                "Tandem attributes the note to the launching clinician; when "
                "testing, launch as a practitioner who is a participant of the "
                "encounter."
            ),
        )

    period = as_object(encounter.get("period"))
    checker.check(
        "encounter.period",
        "Encounter.period.start is populated",
        "§4.2",
        period is not None and bool(period.get("start")),
        severity=CheckSeverity.WARN,
        detail="Used as the time context on the written-back DocumentReference.",
    )
    status = encounter.get("status")
    checker.check(
        "encounter.status",
        "The encounter is active/in-progress at recording time",
        "§4.2",
        status in ("in-progress", "arrived", "triaged", "onleave", "planned"),
        severity=CheckSeverity.WARN,
        detail=(
            f"status: {status!r}. Clinicians launch Tandem from the open "
            "encounter they are documenting; when testing, launch from an "
            "encounter that is not yet finished."
        ),
    )
    return encounter, step


def _encounter_period(encounter: dict[str, object] | None) -> dict[str, str]:
    now_iso = datetime.now(UTC).isoformat(timespec="seconds")
    period = as_object(encounter.get("period")) if encounter else None
    start = as_str(period.get("start")) if period else None
    if period is not None and start is not None:
        return {"start": start, "end": as_str(period.get("end")) or now_iso}
    return {"start": now_iso, "end": now_iso}


def build_document_reference(
    *,
    patient_id: str,
    encounter_id: str | None,
    fhir_user: str | None,
    encounter: dict[str, object] | None,
) -> dict[str, object]:
    """A sample clinical note shaped exactly like guide §5.1."""
    now_iso = datetime.now(UTC).isoformat(timespec="seconds")
    note_b64 = base64.b64encode(SAMPLE_NOTE_TEXT.encode()).decode()
    document: dict[str, object] = {
        "resourceType": "DocumentReference",
        "status": "current",
        "docStatus": "final",
        "type": {
            "coding": [
                {
                    "system": "http://loinc.org",
                    "code": "11506-3",
                    "display": "Progress note",
                    "userSelected": True,
                }
            ],
            "text": "Progress note",
        },
        "subject": {"reference": f"Patient/{patient_id}"},
        "date": now_iso,
        "content": [
            {
                "attachment": {
                    "contentType": "text/plain;charset=utf-8",
                    "data": note_b64,
                    "title": SAMPLE_NOTE_TITLE,
                    "creation": now_iso,
                }
            }
        ],
    }
    if fhir_user is not None:
        document["author"] = [{"reference": fhir_user}]
    if encounter_id is not None:
        document["context"] = {
            "encounter": [{"reference": f"Encounter/{encounter_id}"}],
            "period": _encounter_period(encounter),
        }
    return document


def build_condition(
    *,
    code: str,
    display: str,
    text: str,
    patient_id: str,
    encounter_id: str | None,
    fhir_user: str | None,
) -> dict[str, object]:
    """A sample encounter diagnosis shaped exactly like guide §5.2."""
    condition: dict[str, object] = {
        "resourceType": "Condition",
        "clinicalStatus": {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
                    "code": "active",
                }
            ]
        },
        "category": [
            {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/condition-category",
                        "code": "encounter-diagnosis",
                        "display": "Encounter Diagnosis",
                    }
                ]
            }
        ],
        "code": {
            "coding": [
                {
                    "system": "http://hl7.org/fhir/sid/icd-10-cm",
                    "code": code,
                    "display": display,
                    "userSelected": True,
                }
            ],
            "text": text,
        },
        "subject": {"reference": f"Patient/{patient_id}"},
        "recordedDate": datetime.now(UTC).isoformat(timespec="seconds"),
    }
    if encounter_id is not None:
        condition["encounter"] = {"reference": f"Encounter/{encounter_id}"}
    if fhir_user is not None:
        condition["recorder"] = {"reference": fhir_user}
    return condition


def check_create_response(
    checker: Checker,
    resource_type: str,
    response: SafeResponse | None,
    *,
    error: str,
    retry: bool,
) -> None:
    """Validate the §5.3 create response (or the §5/§6 idempotent-retry shape)."""
    prefix = f"writeback.{resource_type.lower()}"
    if not checker.check(
        f"{prefix}.reachable",
        f"The FHIR server responded to POST /{resource_type}",
        "§5",
        response is not None,
        detail=error,
    ):
        return
    assert response is not None

    if retry:
        checker.check(
            f"{prefix}.retry_status",
            f"Retried POST /{resource_type} is handled idempotently "
            "(200/201 update-or-create, or 409 returning the existing resource)",
            "§5, §6",
            response.status_code in (200, 201, 409),
            detail=f"Got HTTP {response.status_code}.",
        )
        return

    checker.check(
        f"{prefix}.status",
        f"POST /{resource_type} returns 201 Created",
        "§5.3",
        response.status_code == 201,
        detail=f"Got HTTP {response.status_code}.",
    )
    checker.check(
        f"{prefix}.location",
        "The Location header contains the created resource URL",
        "§5.3",
        bool(response.headers.get("location")),
        detail=f"Location: {response.headers.get('location')!r}",
    )
